### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by e-minguez** [RedHatEMEA/RHEV-Tools#4]
Some messages aren't in english:

https://github.com/RedHatEMEA/RHEV-Tools/blob/master/general/rhevtools.py#L555
https://github.com/RedHatEMEA/RHEV-Tools/blob/master/general/rhevtools.py#L578

**Comment by iranzo** [comment]
Edu, submit a patch and a pull request and we'll commit them ;-)

**Comment by karmab** [comment]
patch submitted :)

On Fri, Jun 5, 2015 at 2:12 PM, Pablo Iranzo Gómez <notifications@github.com

**Comment by iranzo** [comment]
Closed by https://github.com/RedHatEMEA/RHEV-Tools/pull/5
